stages:
  - build

build_pdf_doc:
  image: ${CI_REGISTRY_IMAGE}/texlive-latex-extra:1
  stage: build
  tags:
    - build
    - internet
  artifacts:
    paths:
      - pdf/
    when: always
    expire_in: 14 day
  script:
    - mkdir -p pdf
    - pdflatex -halt-on-error -interaction=nonstopmode -output-directory pdf Xtensa.tex
