stages:
  - build

image: ${CI_DOCKER_REGISTRY}/llvm-build:1-6ff17268

.use_ci_tools: &use_ci_tools |
  curl -sSL ${CIT_LOADER_URL} -o cit_loader.sh && sh cit_loader.sh
  source citools/import_functions

.add_gitlab_key: &add_gitlab_key |
  cit_add_ssh_key "${GITLAB_KEY}"


before_script:
  - *use_ci_tools
  - *add_gitlab_key

build_pdf_doc:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-toolchain
  artifacts:
    paths:
      - pdfdoc/
    when: always
    expire_in: 14 day
  script:
    sudo apt-get -y  install curl
    sudo apt-get -y install texlive-latex-extra
    pdflatex Xtensa.tex
    mkdir -p pdfdoc
    mv Xtensa.tex pdfdoc/

