stages:
  - build

build_pdf_doc:
  image: ${CI_REGISTRY_IMAGE}/texlive-latex-extra:1
  stage: build
  tags:
    - build
    - internet
  artifacts:
    paths:
      - pdf/
    when: always
    expire_in: 14 day
  script:
    - mkdir -p pdf
    - echo "\\newcommand{\\gitinfo}{Version $(git describe --always), $(git log -1 --pretty=format:%ad --date=short)}" > revision.tex
    # run latex twice to generate and use the .aux file
    - for i in 1 2; do pdflatex -halt-on-error -interaction=nonstopmode -output-directory pdf Xtensa.tex; done
