stages:
  - build

build_pdf_doc:
  image: ${CI_REGISTRY_IMAGE}/texlive-latex-extra:3
  stage: build
  tags:
    - build
    - internet
  artifacts:
    paths:
      - Xtensa.pdf
    when: always
    expire_in: 14 day
  script:
    - ./build.sh
