stages:
  - build

image: ubuntu:14.04

.add_gitlab_key: &add_gitlab_key |
  cit_add_ssh_key "${GITLAB_KEY}"

before_script:
  - *use_ci_tools
  - *add_gitlab_key

build_pdf_doc:
  stage: build
  artifacts:
    paths:
      - pdfdoc/
    when: always
    expire_in: 10 day
  script:
    sudo apt install texlive-latex-extra
    pdflatex Xtensa.tex
    mkdir -p pdfdoc
    mv Xtensa.tex pdfdoc/

